{% set name = "asammdf" %}
{% set version = "8.8.2" %}
{% set sha256 = "d9ef4bb48794ae1589b1d91006dfd60695f53e1028562e5c37532b86cdac2961" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - scikit-build-core
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel
    - numpy >=2.0
    - python-build
  run:
    - python >=3.10
    - numpy >=2.0
    - pandas
    - numexpr
    - matplotlib-base
    - wheel
    - canmatrix >=1.2
    - chardet >=7.0.0
    - lxml
    - natsort
    - lz4
    - typing_extensions
    - python-isal
    - zstd
    - deflate 

test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports. 
  requires:
    - pytest
    - setuptools
    - {{ compiler('c') }}
  imports:
    - asammdf


about:
  home: https://github.com/danielhrisca/asammdf
  license: LGPLv3+
  license_family: LGPL
  license_file: LICENSE
  summary: ASAM MDF measurement data file parser
  description: |
    *asammdf* is a fast parser/editor for ASAM (Associtation for Standardisation of Automation and Measuring Systems) MDF (Measurement Data Format) files. \n\n*asammdf* supports MDF versions\
    \ 2 (.dat), 3 (.mdf) and 4 (.mf4). \n\n*asammdf* works on Python >= 3.7\
    GUI available that is based on pyqtgraph and PyQt5
  doc_url: http://asammdf.readthedocs.io/en/master
  dev_url: https://github.com/danielhrisca/asammdf

extra:
  recipe-maintainers:
    - danielhrisca
