{% set name = "asammdf" %}
{% set version = "7.0.3" %}
{% set sha256 = "45c6b3d56ecaeffefe726c49b4a8d971354ae1d4a449033f7b6d4f4e3c32f9dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - asammdf = asammdf.gui.asammdfgui:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
    - numpy >=1.21
  run:
    - python >=3.7
    - numpy >=1.21
    - pandas
    - numexpr
    - matplotlib-base
    - wheel
    - canmatrix
    - chardet
    - lxml
    - natsort
    - lz4
    - typing_extensions
    - python-isal

test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports. 
  requires:
    - pytest
    - setuptools
    - {{ compiler('c') }}
  imports:
    - asammdf


about:
  home: https://github.com/danielhrisca/asammdf
  license: LGPLv3+
  license_family: LGPL
  license_file: LICENSE
  summary: ASAM MDF measurement data file parser
  description: |
    *asammdf* is a fast parser/editor for ASAM (Associtation for Standardisation of Automation and Measuring Systems) MDF (Measurement Data Format) files. \n\n*asammdf* supports MDF versions\
    \ 2 (.dat), 3 (.mdf) and 4 (.mf4). \n\n*asammdf* works on Python >= 3.7\
    GUI available that is based on pyqtgraph and PyQt5
  doc_url: http://asammdf.readthedocs.io/en/master
  dev_url: https://github.com/danielhrisca/asammdf

extra:
  recipe-maintainers:
    - danielhrisca
